version: '3.5'

services:
  api:
    container_name: api
    build: .
    env_file:
      - .env
    command: sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn mad.wsgi:application --bind 0.0.0.0:8000 --timeout=120
      "
    ports:
      - 8000:8000
    volumes:
      - ./static/:/mad/static/
      - ./media/:/mad/media/
    depends_on:
      - db
    restart: always

  db:
    container_name: postgredb
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres-data: